### ISSUE TITLE
(old) clang complains about our version number

### ISSUE THREAD

**Issue by lindsayad** [libMesh/TIMPI#56]
See [this](https://travis-ci.org/github/libMesh/TIMPI/jobs/740976991) for example. I fixed a similar problem for version `1.2.0` in 91c38b2

**Comment by roystgnr** [comment]
This is fixed more robustly in https://github.com/libMesh/autoconf-submodule/commit/c297dd35fa98743905e611d8afc6edbf33de406c - just haven't gotten around to updating the submodules yet.

**Comment by roystgnr** [comment]
I wouldn't mind a belt-and-suspenders fix with the version number changed in configure.ac too, though.
